from archon.service_catalog.base import Service

SERVICES: list[Service] = [
    Service(
        name='Amazon SageMaker',
        provider='aws',
        category='ai_ml',
        description='Fully managed ML platform for building, training, and deploying models',
        use_cases=['ML model training', 'Model hosting', 'ML pipelines', 'Feature engineering'],
        pricing_model='Per-hour for notebooks, training instances, and endpoints',
        limitations=['Cost can scale quickly', 'Requires ML expertise'],
        typical_latency='Milliseconds for inference',
        compliance=['SOC', 'ISO 27001', 'HIPAA'],
    ),
    Service(
        name='Amazon Bedrock',
        provider='aws',
        category='ai_ml',
        description='Fully managed service for foundation models from leading AI companies',
        use_cases=['Generative AI', 'Chatbots', 'Text generation', 'Code generation'],
        pricing_model='Per-token for inference, per-hour for fine-tuning',
        limitations=['Model availability varies by region', 'Limited customization vs self-hosted'],
        typical_latency='Variable by model',
        compliance=['SOC', 'ISO 27001', 'HIPAA'],
    ),
    Service(
        name='Vertex AI',
        provider='gcp',
        category='ai_ml',
        description='ML platform for building, deploying, and scaling ML models',
        use_cases=['ML training', 'Model serving', 'AutoML', 'Generative AI'],
        pricing_model='Per-hour, per-token, or per-node depending on service',
        limitations=['Cost management', 'GCP-only ecosystem'],
        typical_latency='Milliseconds for inference',
        compliance=['SOC', 'ISO 27001', 'HIPAA'],
    ),
    Service(
        name='Azure Machine Learning',
        provider='azure',
        category='ai_ml',
        description='Enterprise ML lifecycle management',
        use_cases=['ML training', 'MLOps', 'Model deployment'],
        pricing_model='Per-compute-hour + workspace costs',
        limitations=['Complexity for simple use cases'],
        typical_latency='Milliseconds for inference',
        compliance=['SOC', 'ISO 27001', 'HIPAA', 'FedRAMP'],
    ),
    Service(
        name='Azure OpenAI Service',
        provider='azure',
        category='ai_ml',
        description='Enterprise access to OpenAI models with Azure security',
        use_cases=['Generative AI', 'Chatbots', 'Content generation', 'Code generation'],
        pricing_model='Per-token pricing',
        limitations=['Limited availability', 'Approval needed for some models'],
        typical_latency='Variable by model',
        compliance=['SOC', 'ISO 27001', 'HIPAA', 'FedRAMP'],
    ),
]
