from archon.service_catalog.base import Service

SERVICES: list[Service] = [
    Service(
        name='Amazon EC2',
        provider='aws',
        category='compute',
        description='Virtual servers in the cloud with resizable compute capacity',
        use_cases=['General purpose computing', 'Web servers', 'Batch processing', 'ML training'],
        pricing_model='Per-hour or per-second billing, reserved instances available',
        limitations=[
            'Requires capacity planning',
            'Manual scaling needed without auto-scaling groups',
        ],
        typical_latency='Milliseconds to provision',
        compliance=['SOC', 'ISO 27001', 'HIPAA', 'PCI DSS'],
    ),
    Service(
        name='AWS Lambda',
        provider='aws',
        category='serverless',
        description='Run code without provisioning servers, pay per request',
        use_cases=['Event-driven workloads', 'API backends', 'Data processing', 'Scheduled tasks'],
        pricing_model='Per-request and per-duration (ms), free tier available',
        limitations=['15 minute timeout', '1MB request payload limit', 'Cold starts'],
        typical_latency='Sub-millisecond (warm), 100ms-1s (cold)',
        compliance=['SOC', 'ISO 27001', 'HIPAA', 'PCI DSS'],
    ),
    Service(
        name='Google Compute Engine',
        provider='gcp',
        category='compute',
        description='Virtual machines running on Google infrastructure',
        use_cases=['General computing', 'Web servers', 'Data analytics', 'Containers'],
        pricing_model='Per-second billing, sustained use discounts, committed use',
        limitations=['Less regional coverage than AWS'],
        typical_latency='Minutes to provision',
        compliance=['SOC', 'ISO 27001', 'HIPAA', 'PCI DSS'],
    ),
    Service(
        name='Google Cloud Functions',
        provider='gcp',
        category='serverless',
        description='Lightweight compute for single-purpose functions',
        use_cases=['Event-driven apps', 'Webhooks', 'API backends'],
        pricing_model='Per-invocation and compute time',
        limitations=['9 minute timeout', 'Limited language support'],
        typical_latency='Sub-second (warm)',
        compliance=['SOC', 'ISO 27001', 'HIPAA'],
    ),
    Service(
        name='Azure Virtual Machines',
        provider='azure',
        category='compute',
        description='Windows and Linux VMs in Azure',
        use_cases=['General computing', 'Windows workloads', 'SQL Server', 'Dev/test'],
        pricing_model='Per-hour billing, reserved instances, spot VMs',
        limitations=['Windows licensing costs', 'Regional availability differences'],
        typical_latency='Minutes to provision',
        compliance=['SOC', 'ISO 27001', 'HIPAA', 'PCI DSS', 'FedRAMP'],
    ),
    Service(
        name='Azure Functions',
        provider='azure',
        category='serverless',
        description='Event-driven serverless compute',
        use_cases=['Event processing', 'API backends', 'IoT backends'],
        pricing_model='Per-execution and per-second',
        limitations=['Function execution time limits', 'Cold start latency'],
        typical_latency='Sub-second (warm)',
        compliance=['SOC', 'ISO 27001', 'HIPAA', 'PCI DSS', 'FedRAMP'],
    ),
]
