from archon.service_catalog.base import Service

SERVICES: list[Service] = [
    Service(
        name='Amazon RDS',
        provider='aws',
        category='database',
        description='Managed relational databases (PostgreSQL, MySQL, SQL Server, etc.)',
        use_cases=['Transactional workloads', 'CRUD applications', 'SaaS backends'],
        pricing_model='Per-hour instance cost + storage + I/O',
        limitations=['Vertical scaling limits', 'Multi-AZ adds cost'],
        typical_latency='Milliseconds',
        compliance=['SOC', 'ISO 27001', 'HIPAA', 'PCI DSS'],
    ),
    Service(
        name='Amazon DynamoDB',
        provider='aws',
        category='database',
        description='Managed NoSQL key-value and document database',
        use_cases=['High-scale web apps', 'Gaming', 'IoT', 'Real-time bidding'],
        pricing_model='Per-table throughput (RCU/WCU) + storage',
        limitations=['Query patterns must be known upfront', 'No joins or complex queries'],
        typical_latency='Single-digit milliseconds',
        compliance=['SOC', 'ISO 27001', 'HIPAA', 'PCI DSS'],
    ),
    Service(
        name='Cloud SQL',
        provider='gcp',
        category='database',
        description='Managed relational databases (PostgreSQL, MySQL, SQL Server)',
        use_cases=['Web applications', 'CMS', 'Business applications'],
        pricing_model='Per-hour instance + storage',
        limitations=['Less regional availability than competitors'],
        typical_latency='Milliseconds',
        compliance=['SOC', 'ISO 27001', 'HIPAA'],
    ),
    Service(
        name='Cloud Spanner',
        provider='gcp',
        category='database',
        description='Globally distributed, strongly consistent relational database',
        use_cases=['Global applications', 'Financial services', 'Inventory systems'],
        pricing_model='Per-node-hour + storage',
        limitations=['Higher cost', 'Overkill for single-region apps'],
        typical_latency='Milliseconds globally',
        compliance=['SOC', 'ISO 27001', 'HIPAA'],
    ),
    Service(
        name='Azure SQL Database',
        provider='azure',
        category='database',
        description='Managed SQL Server in the cloud',
        use_cases=['Enterprise applications', 'SQL Server migrations', 'ERP/CRM'],
        pricing_model='Per-hour DTU/vCore + storage',
        limitations=['SQL Server specific', 'Licensing complexity'],
        typical_latency='Milliseconds',
        compliance=['SOC', 'ISO 27001', 'HIPAA', 'PCI DSS', 'FedRAMP'],
    ),
    Service(
        name='Azure Cosmos DB',
        provider='azure',
        category='database',
        description='Globally distributed NoSQL database with multi-model support',
        use_cases=['Global apps', 'IoT', 'Real-time analytics'],
        pricing_model='Per-RU throughput + storage',
        limitations=['Higher cost for guaranteed performance', 'Learning curve for API choices'],
        typical_latency='Single-digit milliseconds',
        compliance=['SOC', 'ISO 27001', 'HIPAA', 'PCI DSS', 'FedRAMP'],
    ),
]
